version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_djchat:/var/lib/postgressql/djchat
    env_file: .env

  redis:
    image: redis:latest
    restart: always
    env_file: .env

  server:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./:/djchat
    ports:
      - "8000:8000"

volumes:
  postgres_data_djchat: